# Generated by Django 4.2.7 on 2023-11-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='write_date',
            field=models.DateField(default=None, null=True, verbose_name='작성날자'),
        ),
    ]
