# Generated by Django 4.2.7 on 2023-11-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_write_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='write_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성날자'),
        ),
    ]
