# Generated by Django 4.2.7 on 2023-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_write_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.CharField(blank=True, max_length=100, verbose_name='로그인해서글을쓴사람'),
        ),
    ]
