# Generated by Django 4.2.7 on 2023-11-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_imagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
